version: "3.9"

services:
  jupyterlab:
    build: .
    container_name: mlflow_lab
    ports: ["8888:8888"]
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on: [mlflow]
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /artifacts
      --host 0.0.0.0 --port 5000
    ports: ["5000:5000"]
    volumes:
      - ./artifacts:/artifacts
      - ./mlruns:/mlruns
    restart: unless-stopped
